version: '3.8'

services:
  ros-rc10:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rc10-robot
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./RC10:/catkin_ws/src/RC10:ro
    privileged: true
    stdin_open: true
    tty: true
    command: /bin/bash

